### ISSUE TITLE
Retry UI

### ISSUE THREAD

**Issue by herbig** [decentdao/fractal-interface#1202]
We have a "retry" empty component in the designs, to be used in the event of an API / graph error.  This would need to be integrated into each list screen.

https://www.figma.com/file/cO1nBoNZCmMKCwCCpyTxfx/%F0%9F%A6%84-Fractal-%7C-Pages-%26-Flows-Master?type=design&node-id=4204-28213&t=Nw2kZI4b2HvrHChj-0

<img width="841" alt="Screenshot 2023-06-05 at 1 30 49 PM" src="https://github.com/decent-dao/fractal-interface/assets/384559/cf5c6a38-685d-4765-acce-51da8433ec36">

**Comment by adamgall** [comment]
I like how we're attempting to give the user more information that things aren't working as expected, and then give them an action to try to fix it.

My take on this, however, is that giving the user a button to "retry" something, that they already told the app they wanted to do, is pretty jarring and shifts the blame of what went wrong to the user.

It puts the onus on the user to fix what's wrong. But really it's the app's problem, not the user's problem.

Are there any other ways we can recover from whatever is going wrong in these situations?

**Comment by tomstuart123** [comment]
I agree. I really want to review how we handle and give information on errors at some point (and has been raised by Shutter team).

Let's keep this open just for now and discuss at standup whether we want to create a new initiative on error handling in the app

**Comment by adamgall** [comment]
I've never seen this issue occur (with the error screen in the screenshot above). Also, given the improvements being made to data availability, it doesn't seem like there's anything specific being called out in this issue that isn't slowly getting fixed anyway. Closing.
