### ISSUE TITLE
Oops! Couldn't find a Safe...

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1336]
![Screenshot 2024-01-24 at 8 22 43 AM](https://github.com/decent-dao/fractal-interface/assets/706929/d0f30f26-8b83-4caf-a5e1-7a37272da440)

Sometimes this message appears when attempting to load a Safe.

In the case of this screenshot, it appeared while on the `app.dev.fractalframework.xyz` domain. I did _not_ have any wallet connected to the site, so I assume that the default network for the `app.dev` framework is Goerli, which is referenced in the error message.

I'm opening this issue for two reasons.

1. Why am I being prompted to refresh the page? If a Safe on Goerli doesn't exist at this address, what will refreshing the page accomplish? (i.e., is "refreshing the page" a bandaid fix on top of a deeper data-availability issue?)
2. Why am I being prompted to change the networks in my wallet? I don't have a wallet connected, so I can't change networks.

**Comment by tomstuart123** [comment]
@adamgall would you agree that point (2) you raised is resolved whilst point (1) is still open

i.e. the app shouldn't now not be unable to open a Safe/DAO when disconnected... but we should still look at how we are handling errors to give more precise feedback. 

If a Safe exists but we're on a wrong chain, I think we should prompt them. If there has been an error, I think we should highlight the data availability issue and ask for a refresh.

Thoughts?
