### ISSUE TITLE
WalletConnect with MPCVault not working cleanly with WalletConnect

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1378]
### Overview

We have some users that are using MPCVault (https://mpcvault.com/), and claiming to have issues voting.

![Image](https://github.com/decent-dao/fractal-interface/assets/706929/1a9eebd5-6128-436d-aea4-8c4609dfd431)

![Image](https://github.com/decent-dao/fractal-interface/assets/706929/56414c45-0b23-445a-83de-4723e650ee80)

We should spend a bit of time testing out this setup on our end.

### Version

Dev (app.dev.fractalframework.xyz/)

**Comment by tomstuart123** [comment]
@adamgall let's chat at standup if there are any updates to this / if more information is needed

**Comment by adamgall** [comment]
According to @Da-Colon , this is not buggy any longer. @tomstuart123 to follow up with users that were originally having issues.

**Comment by adamgall** [comment]
The user that was having a problem with MPCVault has confirmed that this issue is no longer a problem. Likely was fixed via #1463
