### ISSUE TITLE
Proposal Description - Enlarge + Markdown

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/fractal-interface#1399]
Notes: This work should happen in the "create proposal template" components, which will soon replace the original "create proposal" components (#1363).

---

As you can see by this request, a Shutter member requested a larger field for proposal creation. 

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/30457d32-754e-4f9d-abff-7b8bac45806c)

You can see here just how small the description field is here

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/b0483ff8-8c92-4fa8-abdb-f6d4127b462c)

They also requested usage of markdown to help with more customisation in creation. 

Note, they might have come to this expectation as you can see below that snapshot offers markdown 

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/32694b0d-9b99-4778-b6ed-c6b47910ff29)

**Comment by adamgall** [comment]
This work should happen on the "Template" workflow.
