### ISSUE TITLE
Snapshot badge behavior

### ISSUE THREAD

**Issue by xraystyle1980** [decentdao/fractal-interface#1426]
The Snapshot badge on an organization's homepage is behaving oddly. 

For instance, on the Decent DAO homepage the Snapshot badge links to `https://app.fractalframework.xyz/daos/decent-dao.eth`
This results in a "No DAO at this address" error. 

Originally, the intention was to link to an org's Snapshot space but now we seem to be linking back to ourselves. Does it make more sense to just turn this into a "Org is also on Snapshot" tooltip?

![CleanShot - Arc - 2024-03-11 3@2x](https://github.com/decent-dao/fractal-interface/assets/18615633/e9f0aafd-01df-43a7-b83d-2de14f81c4dd)
![CleanShot - Arc - 2024-03-11 2@2x](https://github.com/decent-dao/fractal-interface/assets/18615633/53464391-b145-4125-ac77-21ef9ad6b207)

**Comment by adamgall** [comment]
Correct, this is fixed, closing.
