### ISSUE TITLE
Implement new Proposal List designs

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1448]
Implement the new Proposal List designs, as created via https://github.com/decent-dao/fractal-interface/issues/1412

**Comment by Da-Colon** [comment]
Update: Design is taking back over this card to cover some edge cases

**Comment by adamgall** [comment]
@Da-Colon @xraystyle1980 if you're both going to own this card, please make sure you both agree on the total "estimated days" and "expected end" dates, which sounds like should be inclusive of all final design work and then the full engineering implementation.

**Comment by xraystyle1980** [comment]
Passing an updated hand off back to dev.
https://www.figma.com/file/dNWxEnscUonneTsNdzn6qZ/Components---Fractal-Design-System-0.0.1?type=design&node-id=10768-905&mode=design&t=2sDnPivRT46edgwK-4
I removed the data visualizations charts
Updated the status badge component to show every option currently in app (would like to discuss how to consolidate)
Called out some new colors, however as we work through the reskin efforts, colors and tokens will change
Added notation around character limit for description

@Da-Colon Calling out that I did not change the estimated time and will leave that for you to update

![Image](https://github.com/decentdao/fractal-interface/assets/18615633/8b8f649d-db63-4531-aa74-04354a6d8f9e)
