### ISSUE TITLE
Display all featured DAOs across networks on the home page

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1451]
How might we make that app homepage network-agnostic such that it displays featured DAOs across all supported networks, with an icon in the "Featured" card UI that shows what network the DAO is on?

Larger scope of work might look like "Featured" becoming an "Explore" experience.

As long as the current "click" behavior stays the same (take user to that DAO within Fractal), this issue is blocked due to the fact that we currently don't chainspace DAOs in the URL and therefore can't auto-switch networks for the user or indicate to them that they're on the wrong network for a given DAO address.

**Comment by Da-Colon** [comment]
This is something I've had in the back of my head for a while creating simple provider hook to let us use other networks as needed versus the one 'hardcoded' in the app.
