### ISSUE TITLE
Investigate Multiple Requests `useERC20Claim`

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/fractal-interface#1456]
There seems to be several additional "too many requests" coming out of ERC20Claim hook when loading a Azorius DAO. We should see what is causing this.

**Comment by adamgall** [comment]
@Da-Colon this issue has two PRs linked to it. As of now, one is merged the other is not. When does this issue get completed?

**Comment by Da-Colon** [comment]
Technically no? since its not technically in develop yet.

Same as my other current branch. the work was branched off this work. While not directly related I had done the work working off the smoother branch. 

This also explains why I could not remove this issue from this branch I guess because of the relationship of the PRs at the time.

**Comment by adamgall** [comment]
Closed as of #1486
