### ISSUE TITLE
Wallet Display in header not center aligned in Mobile

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/fractal-interface#1458]
![Image](https://github.com/decent-dao/fractal-interface/assets/38386583/f3162a01-6666-48a1-8c33-90307a828f79)

**Comment by adamgall** [comment]
Looks good in the reskin, though, so going to close this issue:



![Image](https://github.com/decentdao/fractal-interface/assets/706929/4a2d3edb-40f6-49ea-ba4d-cc81dddf4246)
