### ISSUE TITLE
Deploy Fractal interface on Base Sepolia

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1460]
This card exists to track the work involved with deploying Fractal (contracts / webapp / subgraphs / etc) on Base and Base Sepolia, _assuming it's even possible_.

Related to:
- `contracts`: https://github.com/decent-dao/fractal-contracts/issues/74
- `subgraph`: https://github.com/decent-dao/fractal-subgraph/issues/9

Let's start there: What goes into making Fractal work on new networks?

---

From @mudrila :

@adamgall We have following doc to implement support on FE side https://github.com/decent-dao/fractal-interface/blob/develop/docs/NETWORK_SUPPORT.md which also mentions deploying contracts. 
And then - there's section in our`fractal-subgraph` repository https://github.com/decent-dao/fractal-subgraph?tab=readme-ov-file#adding-network-support

So effectively, we need to go through following list:
1. Deploy contracts to Base
2. Publish new version with deployed contracts addresses/ABIs to `fractal-contracts` NPM package
3. Deploy Subgraph to Base following README from `fractal-subgraph` repo
4. Implemented changes listed in https://github.com/decent-dao/fractal-interface/blob/develop/docs/NETWORK_SUPPORT.md

**Comment by Da-Colon** [comment]
Update: Currently Deploying to Base Sepolia.

Once testing has been completed, work will beging to deploy to Base mainnet
