### ISSUE TITLE
Create DAO - add snapshot space - character limit / helper text

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/fractal-interface#1470]
Right now, in the app to create a dao AND in the settings page, it asks us in the helper text of the snapshot piece only to add the ENS name (e.g. example.eth)

![Image](https://github.com/decentdao/fractal-interface/assets/31554133/e0bc9da0-78ca-4da5-be0c-e463d3043cce)

To fix a bug way back, we made a change to have the entire snapshot URL be the link that is required (e.g. https://snapshot.org/#/example.eth)

**Issue #1** - currently the helper text is giving them wrong info. if they just put the ENS in, we won't recognise and display the snapshot proposals in the dao if the proposal passed

**Issue #2** - there is a character limit on the input field for the 'Create a DAO' flow. This limit probably worked for the prior 'just ENS'.... but for the entire URL that is now required, it doesn't work. Note this issue doesn't appear in the DAO settings area where you can also update the snapshot url

e.g. when copying Decent's snapshot URL in as a test (e.g. https://snapshot.org/#/decent-dao.eth) I get the below

![Image](https://github.com/decentdao/fractal-interface/assets/31554133/d6dc8540-d140-48b6-9c8a-62955a59384a)

**Comment by adamgall** [comment]
We should also tackle the part where we're apparently requiring a full URL to Snapshot in that input box. That's dumb, all we need is the ENS name of the Snapshot Space. There will likely be some backwards compatibility code needed but whatever.

**Comment by DarksightKellar** [comment]
> We should also tackle the part where we're apparently requiring a full URL to Snapshot in that input box. That's dumb, all we need is the ENS name of the Snapshot Space. There will likely be some backwards compatibility code needed but whatever.

@adamgall Does that mean the bug referenced in this issue's description is no longer present and the helper text ("example.eth") is, in fact, NOT wrong info?

**Comment by DarksightKellar** [comment]
Actually what *is* the bug here? Besides removing the character limit on that input field, everything else seems to be working as far as I can tell with my limited context. How do I make sure I'm testing this right? cc @tomstuart123

**Comment by tomstuart123** [comment]
Kelvin, Kirill and I spoke. 

We discussed going back to ENS for now as to @adamgall 's point

Then I'll a PR now in the backlog to explore a next implementation that supports a full URL (so snapshot testnet site can be linked too) as well as the ENS. We would do the input field validation. More to come

**Comment by adamgall** [comment]
We could also just choose to explicitly not support Snapshot’s “
testnet.snapshot.org” instance.

Like, if you’re using fractal, and want to link a Snapshot site, it needs
to be a real one where the ENS name lives on mainnet.

Not even sure how well Snapshot themselves support it, considering their
docs say that their testnet site uses Goerli for ENS names.

https://docs.snapshot.org/user-guides/spaces/create
