### ISSUE TITLE
Investigate `useProposalCountdown`

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1498]
This needs some more research first. @Da-Colon please update this comment when you learn more.

**Comment by tomstuart123** [comment]
@adamgall any one liner you can give me on what 'useProposalCountdown' gives opportunity for?

**Comment by adamgall** [comment]
Nope, but hopefully @Da-Colon can! I believe I opened this up at his request, or during a conversation with him, or something. I don't recall the context of why this issue was opened.

**Comment by adamgall** [comment]
> @adamgall any one liner you can give me on what 'useProposalCountdown' gives opportunity for?

@tomstuart123 Nope, but hopefully @Da-Colon can! I believe I opened this up at his request, or during a conversation with him, or something. I don't recall the context of why this issue was opened.

**Comment by Da-Colon** [comment]
This is safe to close. It was more of a reminder to continue looking into `useProposalCountdown` hook to ensure that its `dispatch` was being used appropriately. I believe for now we have this working correctly and this issue can be closed
