### ISSUE TITLE
Update Text

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/fractal-interface#1507]
![Image](https://github.com/decentdao/fractal-interface/assets/38386583/3d219628-8b8d-4887-a146-b99c360a005f)

When User has already voted this UI shows. This is a little confused as it looks like the user can cast a vote, but meant to mean that a user has already casted their vote

**Comment by Da-Colon** [comment]
@nicolaus-sherrill @xanaramoss @xraystyle1980

**Comment by nicolaus-sherrill** [comment]
@xraystyle1980 can you confirm that we have disabled button states designed, update screens that show this pattern in Figma, and close this issue out?
