### ISSUE TITLE
Proposal Template Fork URL Not properly structured

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/fractal-interface#1526]
When trying to fork an existing template, it sends you to the Opps page. Looking closing at the URL. it appears the the url isn't being constructed properly where as a second query is seperated by a `&`. 

following the `?dao=""` query it is currently "~?templateHash=""` versus `~&templateHash=""`

![Image](https://github.com/decentdao/fractal-interface/assets/38386583/34b2ec6b-1d69-46a2-95db-9298659f5576)

**Comment by adamgall** [comment]
Fixed via #1527
