### ISSUE TITLE
[reskin] App Layout

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/fractal-interface#1560]
Figma (DAO Home): https://www.figma.com/file/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?type=design&node-id=0-1&mode=design&t=CLI7RbuekARTIO74-0

Combining Sidebar and Header into a single task as the overall goal would be the 'layout' as Header and sidebar will both need to be adjusted. This can be broken up into separate PRs (if needed).

- [x] Replace Fractal Logo with Decent Logo (Asset may need to be updated in Decent-UI)
- [x] Update Header Color and Fonts removing/replacing any leftover from old tokens
- [x] Update Sidebar styles to match Figma Designs. This includes the updated `hover` functionality.
- [x] Update Sidebar icons. Find icons through `@phosphor-icons/react` library. Find name here: https://www.figma.com/file/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?type=design&node-id=288-1435&mode=design&t=pAOJpRB1rRSAe7PB-0
- [x] Update Wallet Menu dropdown
- [x] Update Favorites Menu Dropdown
- [x] Update Search Bar styles (Ask if designs (colors/font) are needed)

**Comment by adamgall** [comment]
Finished, closing
