### ISSUE TITLE
[reskin] Update Proposal List 

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/fractal-interface#1563]
Figma (Proposal List): https://www.figma.com/file/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=95%3A2334&mode=dev

This one should be quick win. This will also update the Proposals that show up on DAO Dashboard as they use same components.

- [ ] Update breadcrumbs to match new style
- [ ] Default style updated
- [ ] Hover Style updated (see dev mode)
- [ ] Badges colors no longer hardcoded, and replace new color names

**Comment by adamgall** [comment]
Closed via #1608
