### ISSUE TITLE
[reskin] Update Proposal Details

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/fractal-interface#1566]
Figma (Proposal Details): https://www.figma.com/file/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?type=design&node-id=64-3590&mode=design&t=0qs91ZixwevlTbgo-0

Should be picked up after #1563, as some components are shared (Mostly the top most details). For now the Responsiveness for these screen will remain the same. Follow up with design for any questions.

- [x] Update Executable code section styles
- [x] Update Proposal Details (left side)
- [x] Update Breakdown section, (removing Circular Proposal Bar)
- [x] Update vote section
- [x] Update Proposal Action section.

**Comment by adamgall** [comment]
Completed, closing
