### ISSUE TITLE
[reskin] Update Create Proposal

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/fractal-interface#1569]
Figma (Create Proposal): https://www.figma.com/file/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?type=design&node-id=104-8737&mode=design&t=0qs91ZixwevlTbgo-0

The main change here is replacing the Preview section with a details section

- [ ] Replace preview section with Details
- [ ] Update styles and typography of main builder

**Comment by adamgall** [comment]
This was merged, manually closing
