### ISSUE TITLE
Restyle the App

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/fractal-interface#1570]
This is the Base issue and will close with the Reskin effort is complete. use the following links to execute on the various work.

## Fractal-UI Storybook: 
https://fractal-ui.netlify.app/?path=/story/design-language-brand-narrative--page

## Figma (Component Library): 
https://www.figma.com/file/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?node-id=0%3A1&mode=dev

## Figma (Handoff): 
https://www.figma.com/file/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=104%3A8737&mode=dev

**Comment by adamgall** [comment]
Closing this
