### ISSUE TITLE
Favorites Menu loading UX is janky

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/fractal-interface#1588]
Having the full vertical length of the menu show up without any visible data next to the lone icons makes the UI look janky and unpolished (see attached screenshot).

We might want to consider showing a centered loading indicator on a full width but empty menu instead, while the data loads.

![Image](https://github.com/decentdao/fractal-interface/assets/7101382/357ef68e-6939-42b2-ab07-03d4c6a870e7)

**Comment by adamgall** [comment]
Yep, fixed in #1622
