### ISSUE TITLE
sort menu has no title

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/fractal-interface#1589]
Note: Screenshot shows lack of title. Was taken on old skin branch, so ignore colours.

I'm wondering if the sort menu was intentionally left without a title, unlike practically every other dropdown menu in the app (execpt the navbar favorites menu, which is totally fine). If not intentional, then we should remember to include it during the reskin work, preferably by whoever ends up taking the menu reskin work.

![Image](https://github.com/decentdao/fractal-interface/assets/7101382/40706132-ec88-4e95-a442-632c9fe45ec9)

**Comment by adamgall** [comment]
Completed as of #1622
