### ISSUE TITLE
Create proposal Input box issues

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/fractal-interface#1600]
In-app:
![Image](https://github.com/decentdao/fractal-interface/assets/7101382/0e539d33-ea73-4868-b2a5-21463f882fe6)

- [x] Hover state border clips on the right side

- [ ] Invalid state does not match design (also missing icon):
![Image](https://github.com/decentdao/fractal-interface/assets/7101382/3bf0e379-6442-4ef9-83da-5da795865b7e)

- [x] Helper text is _probably_ slightly too large (visual check only, might be wrong there)
![Image](https://github.com/decentdao/fractal-interface/assets/7101382/9ca19c4a-4c5e-40a8-821d-2d9a9c68b744)

**Comment by adamgall** [comment]
Completed, closing
