### ISSUE TITLE
Specified Divider top colour doesn't jive well with most default backgrounds

### ISSUE THREAD

**Issue by DarksightKellar** [decentdao/fractal-interface#1601]
This is a very zoomed in view of a Divider component as seen on Figma. It's got a colour that is clearly different from the background. This colour does not seem seem to vary depending on which background it is against. Colour specified for the top border is `neutral-1` (#161219).

![Image](https://github.com/decentdao/fractal-interface/assets/7101382/8fdfd5ae-4c0f-4245-85d9-44b9f4e9616d)

However, this is the exact same colour for the background of most components:
![Image](https://github.com/decentdao/fractal-interface/assets/7101382/c42990ef-cb16-4d26-980e-7ae7acbe1d03)

... causing the resulting UI to look like this: 
![Image](https://github.com/decentdao/fractal-interface/assets/7101382/89e6ec22-340e-42df-93f3-6293ee93b786)

... instead of this:
![Image](https://github.com/decentdao/fractal-interface/assets/7101382/61458aaf-ffa6-43ae-957d-4c97ac3e3e11)

Non-dark parts of the app look fine though:
![Image](https://github.com/decentdao/fractal-interface/assets/7101382/2020f463-fb37-4640-a5e1-9fb91c18ddf0)

**Comment by xraystyle1980** [comment]
Thanks for catching this @DarksightKellar. I think the best path forward is to update the component to work on all the backgrounds. New component will most likely require a new color token. Will test new component in design today (April 25) before handing off a new one with new color token.
