### ISSUE TITLE
Reskin the Error page (`ErrorFallback.tsx`)

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1628]
![Screenshot 2024-05-01 at 12 54 34 PM](https://github.com/decentdao/fractal-interface/assets/706929/54d7ed28-f585-4361-8a96-cdd830aad609)

- remove "ask devs to do something" link
- colors and fonts and maybe use a bigger icon

**Comment by adamgall** [comment]
There are designs for this Error Page in the Figma Handoff

**Comment by adamgall** [comment]
@DarksightKellar are you working on this one?

**Comment by DarksightKellar** [comment]
Yeah I had a local WIP branch for this before the bug bash. I'll have to wrap it up.

**Comment by adamgall** [comment]
@decentdao/design i'm looking at Figma, the text weight is 450. in our `decent-ui` repo's design system, none of our text styles use a weight of 450.

**Comment by adamgall** [comment]
@decentdao/design can you please give us a full size SVG export of the tool image?

**Comment by xraystyle1980** [comment]
> @decentdao/design can you please give us a full size SVG export of the tool image?

If this is still needed here it is
![Tools Illustration](https://github.com/decentdao/fractal-interface/assets/18615633/cbf896f9-8226-442c-8451-71e321f5b97e)

**Comment by xraystyle1980** [comment]
> @decentdao/design i'm looking at Figma, the text weight for both title and body is 450. in our `decent-ui` repo's design system, none of our text styles use a weight of 450. instead of handrolling the typography in figma, can you please be sure to utilize an already defined style?

We use the `normal` weight for body and display. The `normal` weight renders at 450. All typography in Figma is connected to a style. Sounds like we have a discrepancy between the designs and the font weights available in the codebase.

**Comment by adamgall** [comment]
Closed via #1794
