### ISSUE TITLE
Update og:image

### ISSUE THREAD

**Issue by mudrila** [decentdao/fractal-interface#1635]
Our current `og:image` still styled in Fractal theming. We need updated one for re-skin

![Image](https://github.com/decentdao/fractal-interface/assets/25801162/314e5a43-c447-471e-af2c-4c967ed2eca1)

**Comment by xanaramoss** [comment]
![OG_Decent](https://github.com/decentdao/fractal-interface/assets/162434678/8f767973-c0bd-497e-bfdf-f09fcbcd0d29)
@mudrila here it goes.

**Comment by nicolaus-sherrill** [comment]
Looks great @xanaramoss! @mudrila can you confirm when this is implemented?

**Comment by adamgall** [comment]
Closed by #1751
