### ISSUE TITLE
Trash icon

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1682]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYmRlNWIwZjAyNDkwMDA4ZGNiODMxIiwiaWQiOiIxMjdjMDZmMy04Y2MwLTQzMjYtYTE1ZC1jMmMxZjc5YzYwMGIifQ==)

Trash can should follow same ghost button style as the Favorites and Settings.
<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Firefox 125.0 on Mac OS 10.15
Viewport:  1454 x 910 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1678.app.dev.fractalframework.xyz%2Fcreate&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=125.0&resolution=1454x910&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1678.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663bde5b0f02490008dcb831&commentID=663bec30ea36e508fc46fff6&resolution=resolved)

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1678#issuecomment-2101498920_

**Comment by nicolaus-sherrill** [comment]
@xraystyle1980 can you jump in here? I didn't have eyes on that piece in the handoff file, so I can't confirm what was there, only my desire here.

@mudrila the ghost button style treatment is a teensy bit more than removing the border, so I'll leave Trice to assist here.

**Comment by xraystyle1980** [comment]
@mudrila Figma updated to use ghost buttons for the trash can
https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=234-26058&t=NnAviDkKGepe7Xxb-4

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1752
