### ISSUE TITLE
Favorite icon

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1685]
These ghost menu buttons should be 1:1 square in shape. Don't have screenshot, but the settings icon is the same.

<img width="51" alt="Screenshot 2024-05-03 at 2 28 07 PM" src="https://github.com/decentdao/fractal-interface/assets/62394931/7bc45f9f-f987-4153-be48-b0f17b8d8fb2">

---

This icon is now showing up super tiny for me

<img width="413" alt="Screenshot 2024-05-08 at 4 35 21 PM" src="https://github.com/decentdao/fractal-interface/assets/706929/c8a438bd-a4e7-45a0-a135-c1efb4afed98">

**Comment by Da-Colon** [comment]
@adamgall This is what you fixed today yeah? Right now since the two pages of component are tied this will be fixed too?

**Comment by adamgall** [comment]
Yep, I'm working on this one.

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1771
