### ISSUE TITLE
Alignment and non-line-breaking issues

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1688]
Mobile Feedback

2) Settings page - signers are too long for the area. Also on modal open, it opens very small compared to the full width
![WhatsApp Image 2024-05-06 at 13 19 05 (1)](https://github.com/decentdao/fractal-interface/assets/31554133/62e23923-ce97-4b2f-ac41-46a1cc08a5b7)
![WhatsApp Image 2024-05-06 at 13 19 05 (2)](https://github.com/decentdao/fractal-interface/assets/31554133/f61db5c8-1fcf-4067-b49f-c1c8337dd52f)

---

Still seeing various alignment and non-line-breaking issues

<img width="570" alt="Screenshot 2024-05-08 at 4 48 55 PM" src="https://github.com/decentdao/fractal-interface/assets/706929/e1d43dd0-ee32-4a9d-aee8-c941ba4c84f5">
<img width="631" alt="Screenshot 2024-05-08 at 4 49 51 PM" src="https://github.com/decentdao/fractal-interface/assets/706929/9261ea1f-05a6-4f0c-a987-c5aa4819d919">
<img width="230" alt="Screenshot 2024-05-08 at 4 50 04 PM" src="https://github.com/decentdao/fractal-interface/assets/706929/77063357-380d-40cd-9f00-c583ac3b01c2">

_Originally posted by @adamgall in https://github.com/decentdao/fractal-interface/pull/1678#pullrequestreview-2046639400_

**Comment by tomstuart123** [comment]
@mudrila can you confirm if picking this up already

**Comment by tomstuart123** [comment]
yep same, am seeing them too.

I think this is where my confusion was @mudrila as not sure a few of your fixes got merged (e.g. this and issue 1723)

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1775
