### ISSUE TITLE
Title tags

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1691]
**Title tags**
Can we have more dynamic title tags? Currently just is “Decent”
Title tags display in browser tabs and bookmarks. Design TBD but we should update to something like
”Decent | Shutter DAO Proposals” or even better just "Shutter DAO Proposals" 
Scope creep idea: user points to their own Favicon

![CleanShot - Arc - 2024-05-08 8@2x](https://github.com/decentdao/fractal-interface/assets/18615633/fedfdc51-e19d-4b64-84db-a1ec72173991)

_Originally posted by @xraystyle1980 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101320311_

**Comment by adamgall** [comment]
@xraystyle1980 we can use the DAO Name in the page title, no problem.

**Comment by xraystyle1980** [comment]
> @xraystyle1980 we can use the DAO Name in the page title, no problem.
> 
> Including the page is doable too of course.

Awesome thank you for the feedback. So we need to agree on a title format @nicolaus-sherrill @tomstuart123

**Comment by tomstuart123** [comment]
Personally just Decent | [DAOName] works for me

Any more and I feel it could get a bit long

@nicolaus-sherrill / @xraystyle1980

**Comment by nicolaus-sherrill** [comment]
Ship it.

**Comment by adamgall** [comment]
Good call, forgot to close this
