### ISSUE TITLE
Executable code preview “Unable to decode transaction data”

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1692]
**Executable code preview “Unable to decode transaction data”** 
Can we have more context around this message? 
Something isn’t working and whether or not it is our app or just a slow network, we should clearly communicate whats going on as much as possible
![CleanShot - Slack - 2024-05-08 2@2x](https://github.com/decentdao/fractal-interface/assets/18615633/e8b45706-ee7d-4514-a66f-e89b8ffde5ac)

_Originally posted by @xraystyle1980 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101312887_

**Comment by Da-Colon** [comment]
Marking as Medium task as it might take some thought on how to capture what the problem is.

**Comment by adamgall** [comment]
The problem is that our frontend was unable to gather the necessary information to provide more context to the user (function name, parameter types, parameter inputs) for the given transaction.

I understand that there might be multiple reasons for that... but does the user really care? Doubt it.

@decentdao/designers @tomstuart123 can you please whip up some better copy (and design?) for us here?

**Comment by tomstuart123** [comment]
Agreed, for now lets not try and be too specific or detailed with the error message

@xraystyle1980 / @nicolaus-sherrill how about we lean into something just a bit more empathetic/human sounding /

@adamgall is there somewhere we can point them where they might be able to decode the data? I don't think so but just checking

**Comment by tomstuart123** [comment]
I feel you @adamgall, thanks

So ye @xraystyle1980 , I think the only upgrade we could explore for now is more human (less cold language) but not urgent if you / @nicolaus-sherrill don't have brainspace

Lets pick up personalised errors/recommendations later

**Comment by nicolaus-sherrill** [comment]
@adamgall As far as better design, if that is an error, we should use a red-colored error state pattern for better visual feedback. (Same colors as the other error messages, but please let me know if a visual is needed.)

For copy, idk, how about "We are unable to retrieve transaction details at this time."

(Is there any way to refresh the data without refreshing the page???)

**Comment by adamgall** [comment]
> @adamgall As far as better design, if that is an error, we should use a red-colored error state pattern for better visual feedback. (Same colors as the other error messages, but please let me know if a visual is needed.)
> 
> For copy, idk, how about "We are unable to retrieve transaction details at this time."
> 
> (Is there any way to refresh the data without refreshing the page???)

@nicolaus-sherrill Well idk if it's really an "error"... there are valid reasons as to why we can't show decoded transaction data to the user which are not an error or anything we can do about.

I like the copy suggestion.

We are already trying to refresh this data in the background.

@decentdao/designers in addition to the copy updates suggested by @nicolaus-sherrill , are there are design changes to this "We are unable to retrieve transaction details at this time." component you'd like to implement?

**Comment by nicolaus-sherrill** [comment]
Once the Safe API Kit upgrade happens, split messaging to one of two possible scenarios:

1. Safe API errors out.
2. Data retrieved could not be made human readable.

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1760
