### ISSUE TITLE
Update solid button variant disabled state

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1693]
**Update solid button variant disabled state**
Execute disabled button doesn’t looks entirely disabled with the lilac text. 
_*Button was originally designed with lilac and build properly. (my bad, y'all)_

[Updated in Design System
](https://www.figma.com/file/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?type=design&node-id=288%3A15125&mode=dev&t=WIRcqCxDLv8aVttV-1)
![CleanShot - Notion - 2024-05-08 2@2x](https://github.com/decentdao/fractal-interface/assets/18615633/d34397a8-8782-4295-8c83-7edafafdb7f5)
_in app_

![CleanShot - Figma - 2024-05-08@2x](https://github.com/decentdao/fractal-interface/assets/18615633/f6fab16d-9d96-484f-bff6-fcb7a9216be7)
_update to use neutral colors across the board_

_Originally posted by @xraystyle1980 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101306515_

**Comment by Da-Colon** [comment]
This will take a quick update to the `decent-ui` repo.
