### ISSUE TITLE
Countdown timer width

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1695]
> ![screenshot](https://camo.githubusercontent.com/e35ce1e7e1fa49107cff73c648168017f228e2501378946fdbf3dadf44d6fea1/68747470733a2f2f6e65746c6966792d636f636f6f6e2e6e65746c6966792e6170702f2e6e65746c6966792f66756e6374696f6e732f66657463683f636f64653d33303726706174683d65794a7a6158526c58326c6b496a6f6959324e685a44466d5a6d55745a4455345a5330304d6a4d344c574a695932457459324d774f544d784e5467314e574e6d496977695a4756776247393558326c6b496a6f694e6a597a596a686d4f575a6a5a4451304e4451774d4441344d7a49774e6a597a49697769615751694f6949345a54566c4d7a526b4e69316c5a4449304c5451314f5449744f44637a59693032595463344d474d774e6d4a684d574d6966513d3d)
> 
> When time is under a minute, all the formatting to indicate units of time disappears. Only shows a number.
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/proposals/3?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bb33843f9a509d4d5eb53&resolution=resolved)

Countdown chip should stay at a fixed width while timer is counting down
![CleanShot - Arc - 2024-05-08](https://github.com/decentdao/fractal-interface/assets/18615633/0326b504-6612-490d-b3a2-8a8f5fd46d71)

## Update with solution

Move the timer _outside_ of the chip.

@decentdao/designers to provide some visual direction.

---

_Originally posted by @xraystyle1980 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101289178_

**Comment by Da-Colon** [comment]
Closing as a duplicate, see #1702

**Comment by adamgall** [comment]
Reopening

**Comment by adamgall** [comment]
from @nicolaus-sherrill in a comment of a different issue: 

https://github.com/decentdao/fractal-interface/issues/1703#issuecomment-2105097108

**Comment by adamgall** [comment]
There are designs for this: https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=2707-11382

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1786
