### ISSUE TITLE
Proposals and Treasury Tiles on DAO Home

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1696]
**Proposals and Treasury Tiles on DAO Home**
When viewing a DAO, clicking on the Proposal and Treasury tiles take user to respective pages. I can understand the intention but the interaction is not entirely thought through. I suggest removing this functionality for now 
![image](https://github.com/decentdao/fractal-interface/assets/18615633/e567e766-6d56-4f36-9bdf-7be776a38553)

_Originally posted by @xraystyle1980 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101274519_

**Comment by Da-Colon** [comment]
Is this a discussion or has this been agreed upon to remove?

**Comment by tomstuart123** [comment]
@nicolaus-sherrill / @adamgall I initially would agree with Trice. It works fine but isn't clearly clickable so removing until more thought is fine

Saying that, @nicolaus-sherrill / @adamgall if anyone disagrees, just highlight and we'll re-review post reskin

**Comment by adamgall** [comment]
To be clear we are talking about removing the links from those components, not the components completely?

@xraystyle1980 @tomstuart123 @Da-Colon

**Comment by tomstuart123** [comment]
correct. removing the functionality that 'if I click a component, it takes me to the wider page that box relates to'. We definitely keep the components :)

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1768
