### ISSUE TITLE
Full width divider

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1698]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiJkMmYyMmFlMy0yMjE3LTQzNmEtODlhZi1mMDE2ZmEyNzI3YWEifQ==)

Divider should be full width in the container.

<details><summary>Browser metadata</summary>

```
Path:      /treasury?dao=eth:0x574f4Bc0ccEbeF9F5B946A13FF16f931c16De22B
Browser:   Firefox 125.0 on Mac OS 10.15
Viewport:  1518 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Ftreasury%3Fdao%3Deth%3A0x574f4Bc0ccEbeF9F5B946A13FF16f931c16De22B&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=125.0&resolution=1518x912&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/treasury?dao=eth:0x574f4Bc0ccEbeF9F5B946A13FF16f931c16De22B) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bb5ba4f86f40babc87b1a&resolution=resolved)

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101062227_

**Comment by Da-Colon** [comment]
@mudrila Did I see this fix in one of your mobile PRs?

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1807
