### ISSUE TITLE
Standardize green address pill behavior

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1699]
This address no longer opens to Github on click. Suggest removing the tooltip on hover. Copy functionality works as expected.
<img width="165" alt="Screenshot 2024-05-03 at 2 52 02 PM" src="https://github.com/decentdao/fractal-interface/assets/62394931/1f08cfda-5f80-4b68-81d3-b4959ce91473">

This behavior should be consistent for all places in the app where we show an address in a green pill.

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2093672219_

**Comment by adamgall** [comment]
Originally commented on by @nicolaus-sherrill :

> @adamgall in regards to the comment about the ghost text buttons & copying to clipboard vs opening in Etherscan, I agree with you — functionality should be the same. Regardless, a tooltip communicating an action to a user should be accurate, so thanks for removing that tooltip for the "copy address" button at the top of the DAO Home page.
> 
> One solution that comes to mind is a different style on hover for actual text links vs buttons — we could throw in an underline on hover and/or drop an angled-northeast-arrow icon at the right to communicate that the user will be taken to a new experience. I'll open a design issue about this for us. @xraystyle1980 @xanaramoss FYI

**Comment by tomstuart123** [comment]
yep as long as it doesn't come up with open in etherscan (i.e only option is to copy address) then this is done :)

**Comment by tomstuart123** [comment]
let me check in when I'm done with a few twitter spaces :)

**Comment by nicolaus-sherrill** [comment]
@mudrila looks good to me!

**Comment by tomstuart123** [comment]
thanks @nicolaus-sherrill
