### ISSUE TITLE
Proposal active time unit display

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1702]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiI4ZTVlMzRkNi1lZDI0LTQ1OTItODczYi02YTc4MGMwNmJhMWMifQ==)

When time is under a minute, all the formatting to indicate units of time disappears. Only shows a number.

## Update with solution

The intention here is to keep the minutes segment, when down to < 1 minute.

Example: if 1 minute and 10 seconds left, display `01:10`
Example: if 10 seconds left, display `00:10`

<details><summary>Browser metadata</summary>

```
Path:      /proposals/3?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2
Browser:   Firefox 125.0 on Mac OS 10.15
Viewport:  1518 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fproposals%2F3%3Fdao%3Dsep%3A0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=125.0&resolution=1518x912&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/proposals/3?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bb33843f9a509d4d5eb53&resolution=resolved)

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101044590_

**Comment by adamgall** [comment]
@nicolaus-sherrill what is your solution?

**Comment by Da-Colon** [comment]
Similar to issue #1695, which I'll go ahead and close.

**Comment by nicolaus-sherrill** [comment]
> @nicolaus-sherrill what is your solution?

I _believe_ current formatting shows seconds counting down like `M:SS m` when we are down to minutes on the timer. Once time goes under a minute, we could preserve that formatting with `0:SS m`.

Ex:
`1:00 m` becomes `0:59 m`

**Comment by adamgall** [comment]
We currently don’t show any units in this display.

**Comment by nicolaus-sherrill** [comment]
<img width="411" alt="Screenshot 2024-05-09 at 1 09 33 PM" src="https://github.com/decentdao/fractal-interface/assets/62394931/413124b6-e1a5-47cf-8084-7133deabed53">

That timer does currently display during an active proposal.

**Comment by adamgall** [comment]
Oh wtf! My bad that must have been in the redesign, it didn’t used to have
those labels.

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1778
