### ISSUE TITLE
Overlapping tooltips

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1703]
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiJjNjRlNmMyYi1lMTQ3LTRkN2QtOTdiNC0wZmViNDNlZjZlZGEifQ==)

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiI2NWU4NzMwZS01OWE2LTRmOTEtOThiZC1lZTZjMGM5NDg4MjcifQ==)

Tool tips are overlapping.
<details><summary>Browser metadata</summary>

```
Path:      /proposals/3?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2
Browser:   Firefox 125.0 on Mac OS 10.15
Viewport:  1518 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fproposals%2F3%3Fdao%3Dsep%3A0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=125.0&resolution=1518x912&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/proposals/3?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bb2f9462d1308438f1db4&resolution=resolved)

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101042897_

**Comment by adamgall** [comment]
@nicolaus-sherrill @xraystyle1980 @xanaramoss 

Use this active Shutter DAO proposal on Mainnet as an example:

https://deploy-preview-1578.app.dev.fractalframework.xyz/proposals/16?dao=eth:0x36bD3044ab68f600f6d3e081056F34f2a58432c4

Hover over the "Active" pill, and the "time remaining" number in that pill.

Notice how we have tooltips which overlap.

What should we do instead here? I would say get rid of the "Time remaining to cast your vote" tooltip that appears when you hover on the time itself.

**Comment by nicolaus-sherrill** [comment]
My take:
Either pop it out to the right where there is a ton of space, or follow Adam's suggestion.

I'd love for the rest of the design team to weigh in.

**Comment by adamgall** [comment]
Thinking "mobile first": will there always be "a ton of space" on the right?

**Comment by nicolaus-sherrill** [comment]
@adamgall honestly, a better question there is how are tooltips even handled on mobile? IDK! I don't see any tooltip action currently happening on mobile.

**Comment by adamgall** [comment]
> @adamgall honestly, a better question there is how are tooltips even handled on mobile? IDK! I don't see any tooltip action currently happening on mobile.

@nicolaus-sherrill you're right. I thought it worked like if you tapped on an element with a tooltip on mobile, the tooltip appeared, but that's not the case.

These fucking tooltips.

Can we just get rid of them all? fuck.

**Comment by nicolaus-sherrill** [comment]
@adamgall final quick-win design decision: Remove the "Time remaining to cast your vote" tooltip on the timer hover.

**Comment by adamgall** [comment]
@nicolaus-sherrill thinking out loud here... when we move the timer outside of the pill, we'll no longer run into this "overlapping tooltip" issue.

The reason the tooltips are currently overlapping is because the elements are nested, and we have the on-hover tooltip triggers on both the parent and child icon.

When we move the timer outside of the pill, we'll have two sibling components with tooltip on-hover triggers, so only one will be active at a time.

With that in mind, should we just keep the this tooltip and close this issue?

**Comment by nicolaus-sherrill** [comment]
@adamgall sounds good to me.

Speaking of, I have a design ready for visual aid, but quick direction for the timer being pulled out of the chip:

12px spacing between chip & timer.
Neutral 7 color for the timer text.

EZPZ

**Comment by adamgall** [comment]
Closing because this issue won't happen after https://github.com/decentdao/fractal-interface/issues/1695 is implemented
