### ISSUE TITLE
Sidebar icon spacing

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1705]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiIzMjVhMTU0ZC0zNTdhLTQ3Y2EtODBiMi0wZjlkNzA3MjNmNDQifQ==)

Spacing around icons should be even on all sides. Square.
<details><summary>Browser metadata</summary>

```
Path:      /home?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2
Browser:   Firefox 125.0 on Mac OS 10.15
Viewport:  1518 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fhome%3Fdao%3Dsep%3A0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=125.0&resolution=1518x912&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/home?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bb27cbf85bd00ac2bb73c&resolution=resolved)

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101039728_

**Comment by adamgall** [comment]
@nicolaus-sherrill looks like even spacing to me. What exactly is wrong?

**Comment by nicolaus-sherrill** [comment]
There's slightly more padding on the left side and it looks slightly vertically squished.

**Comment by adamgall** [comment]
Closing as a duplicate of https://github.com/decentdao/fractal-interface/issues/1667
