### ISSUE TITLE
Do not display Module transactions

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1712]
Styling of transactions vs proposals is off. I'm not 100% certain what information needs to be displayed here, but my take is that these transactions should use the same proposal title text style for consistency.

<img width="1298" alt="Screenshot 2024-05-03 at 2 53 29 PM" src="https://github.com/decentdao/fractal-interface/assets/62394931/76db98b3-b74b-4bd2-8105-1811b4ebe6dd">

Link hover is wonky here, too:
<img width="154" alt="Screenshot 2024-05-03 at 2 58 29 PM" src="https://github.com/decentdao/fractal-interface/assets/62394931/e01987d1-ef33-4d34-a2fb-0a8ddd9ca323">

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2093679056_

**Comment by Da-Colon** [comment]
The link being wonky is covered by another Issue. 

As far as the main issue here. The module transaction are included when we pull transaction from the safe API. These activities are included to my understand when safe module is interacted with. Honestly we can properly remove these as these can be confusing for general users and all interaction would be covered by a proposal anyway.

**Comment by nicolaus-sherrill** [comment]
Let's remove them!

**Comment by tomstuart123** [comment]
late to the game but agree with this

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1776
