### ISSUE TITLE
Trashcan icon during Safe creation

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1713]
Trashcan icon during Safe creation should follow the other ghost-button icons (settings & favorite) <img width="1160" alt="Screenshot 2024-05-03 at 2 59 26 PM" src="https://github.com/decentdao/fractal-interface/assets/62394931/3a2e5b01-a99c-4f6b-8d27-ee1b9e99784a">

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2093680208_

**Comment by Da-Colon** [comment]
Duplicate Issue, see #1682
