### ISSUE TITLE
Hover effect on parent dao breadcrumb

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1714]
On child safe home page, the hover effect for the parent dao breadcrumb triggers across the entire content window width instead of just the text. Is this intentional? I kinda like it, but we would need to cook up a different design to give that space more presence.

<img width="1136" alt="Screenshot 2024-05-03 at 3 02 57 PM" src="https://github.com/decentdao/fractal-interface/assets/62394931/3dcadf28-8fd4-4305-a489-42ae5275cce4">

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2093685918_

**Comment by adamgall** [comment]
@nicolaus-sherrill can you explain a bit more about what you're seeing and what should change?

**Comment by adamgall** [comment]
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYmVlNWZhYTA4OWIwMDA5ODJhODg4IiwiaWQiOiJjNThlOTQyMS0xNmViLTRiMmEtOTM2Yi1mYjcxNzA2MzE1NzIifQ==)

**Comment by nicolaus-sherrill** [comment]
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYmVlNWZhYTA4OWIwMDA5ODJhODg4IiwiaWQiOiI2MWViMTM1MC02YjYxLTQyMTctOWU0Ny1kN2ZjZDE3MDA3MjUifQ==)

For more context, this recording shows the hover effect happening across the full width of the content container. Is this intended behavior, or should the hover + ability to click only happen when hovering over the text?

**Comment by adamgall** [comment]
I would agree that the link should not span the whole width.

**Comment by nicolaus-sherrill** [comment]
Coolio

The full-width hover gave me an idea to lean into it visually w/ some kinda cropped card preview from the top nav, but to save time and keep focus let's not worry about it.

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1779
