### ISSUE TITLE
Long links spilling out of container

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1715]
Looks like extra long links are spilling out of their container instead of wrapping in proposal details

<img width="1138" alt="Screenshot 2024-05-03 at 3 11 44 PM" src="https://github.com/decentdao/fractal-interface/assets/62394931/1be8b50f-b845-4226-afc9-d85665298c25">

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2093696520_

**Comment by Da-Colon** [comment]
There are several issues related to Links in the app. that might be solved together. I won't close this one as this is a different spot but just wanted to note there are issues covering this.

**Comment by tomstuart123** [comment]
Thanks @Da-Colon . @mudrila are you working on this link or just other areas of the app

**Comment by adamgall** [comment]
![Image](https://github.com/decentdao/fractal-interface/assets/706929/c2d42e96-a1f7-4c5d-b1a9-b563dd0431a2)

This issue is confirmed fixed

**Comment by tomstuart123** [comment]
nice, thanks @mudrila
