### ISSUE TITLE
App crashes when manually typing address in Search Bar

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1716]
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiJhYWUyNjY3NS0xODU0LTQxOTItYTZkZC0yMWI3ZGE0NWE5Y2QifQ==)

**Comment by Da-Colon** [comment]
This seems like an update made to `throw` that isn't being caught properly

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1747
