### ISSUE TITLE
Treasury page with long NFT IDs goes really wide

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1717]
3) ShutterDAO's treasury page seemed stuck on 'full width mobile view' even when on desktop. On further scroll, it appeared the issue was due to very long link for NFTs. 
![Screenshot 2024-05-06 at 13 23 17](https://github.com/decentdao/fractal-interface/assets/31554133/b6d2bdf5-ac9b-43cf-a9f6-6405b30031d7)
![Screenshot 2024-05-06 at 12 01 03](https://github.com/decentdao/fractal-interface/assets/31554133/8fbd69e5-8f9c-4843-9ff3-75d055e5eb17)

_Originally posted by @tomstuart123 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2096389291_

**Comment by nicolaus-sherrill** [comment]
@mudrila Long links aren't overflowing the container anymore, but I'm seeing some text cutoff happening.
<img width="501" alt="Screenshot 2024-05-09 at 12 32 48 PM" src="https://github.com/decentdao/fractal-interface/assets/62394931/2fae9bf3-13f5-45a6-85bd-206896363338">

**Comment by tomstuart123** [comment]
ye looking much better but I'm also getting the small cut off @nicolaus-sherrill

**Comment by nicolaus-sherrill** [comment]
As long as that cutoff is captured elsewhere, sounds good to me.
