### ISSUE TITLE
"Approved" pill doesn't need hover state

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1718]
6) @nicolaus-sherrill / @xraystyle1980 is the 'Approved' button meant to have a hover state. If so, does it really need one
![Screenshot 2024-05-06 at 12 47 54](https://github.com/decentdao/fractal-interface/assets/31554133/765680bd-33af-4c5d-8a57-6762f41be8d3)
![Screenshot 2024-05-06 at 12 47 50](https://github.com/decentdao/fractal-interface/assets/31554133/9e796193-d2f6-4cc4-8c76-8d230fbcbfc4)

_Originally posted by @tomstuart123 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2096391380_

**Comment by nicolaus-sherrill** [comment]
@xraystyle1980 you worked on these chips w/ hover states. What was your thinking here? I don't have a strong opinion on the hovers, and lean into the principle of including something only if it is providing feedback to the user.

**Comment by xraystyle1980** [comment]
> @xraystyle1980 you worked on these chips w/ hover states. What was your thinking here? I don't have a strong opinion on the hovers, and lean into the principle of including something only if it is providing feedback to the user.

the original intention was depth and delight. Depth by making the entire app feel "more alive", same with delight. Just adding polish

**Comment by nicolaus-sherrill** [comment]
¯\_(ツ)_/¯

Nothing to change here, then, unless there's a good argument to remove it. 
@tomstuart123 what about the hover state made you flag this for feedback?

**Comment by tomstuart123** [comment]
just lacking functionality. I get the depth and delight angle though

Lets close this issue
