### ISSUE TITLE
DAO Hierarchy level indication

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1720]
8) @xraystyle1980 / @nicolaus-sherrill  for the dao hierarchy, I currently visually have no way of knowing (beyond the title) which level of the hierarchy I am currently in. Compare this to the original below with the strong underline. Is this intended functionality? If so, I'd question it especially for Myosin DAO who has three levels
![Screenshot 2024-05-06 at 13 05 04](https://github.com/decentdao/fractal-interface/assets/31554133/fcaf2bb2-b708-4f87-bfdd-86161d5d1950)
![Screenshot 2024-05-06 at 13 35 58](https://github.com/decentdao/fractal-interface/assets/31554133/748b5fb0-fe1b-4a55-b342-a89958db5e2e)

_Originally posted by @tomstuart123 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2096395374_

**Comment by nicolaus-sherrill** [comment]
Removing my assignment because @xraystyle1980 has started on this.

**Comment by xraystyle1980** [comment]
Hierarchy desktop design below
![image](https://github.com/decentdao/fractal-interface/assets/18615633/e1d5b784-7e49-4d32-8921-2682bb9cc1ed)

In Figma
https://www.figma.com/design/7zqmHjIfoxVDDx7wZw6xqI/Design-%26-Feedback?node-id=1068-7808&t=1l26jxxW5QHFobpF-4

@nicolaus-sherrill if you're good with this I'll move to handoff

**Comment by nicolaus-sherrill** [comment]
@xraystyle1980 ship it.

**Comment by tomstuart123** [comment]
yes, please handoff. This is great @xraystyle1980

**Comment by xraystyle1980** [comment]
Ready to rock. Hierarchy desktop designs are updated in the [handoff file](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?m=auto&node-id=122%3A13464&t=oGw4IeLxgEojCGnO-1).

[In the Design System](https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?m=auto&node-id=3044%3A9442&t=W1iZMJUKamdroiay-1)
*Note I added the 3 dots menu button to the designs as they were previously absent. Medium `icon-button` component used. 
![image](https://github.com/decentdao/fractal-interface/assets/18615633/945f5631-d810-44bf-a6c7-6ccbe030f56a)
![image](https://github.com/decentdao/fractal-interface/assets/18615633/1abd6ea1-cc00-4458-80c0-12f82d16f61c)

**Comment by Da-Colon** [comment]
Didn't noticed your change there to re-add the settings menu. Now someone else correct me but do we need this functionality to be on the Hierarchy page (my Opinion, no)? If yes, should it match the gear icon on DAO Dashboard?

**Comment by adamgall** [comment]
No setting gear on those children plz

**Comment by xraystyle1980** [comment]
> Didn't noticed your change there to re-add the settings menu. Now someone else correct me but do we need this functionality to be on the Hierarchy page (my Opinion, no)? If yes, should it match the gear icon on DAO Dashboard?

Yep good catch. [Updated in Figma](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?m=auto&node-id=122%3A13462&t=JZsXE75rQ5gEjGv7-1)

[Updated Prototype
](https://www.figma.com/proto/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?page-id=122%3A13462&node-id=2746-5942&viewport=899%2C-77%2C0.21&t=VkGEryQ1YNCJ0WB1-1&scaling=scale-down&starting-point-node-id=2746%3A5942&show-proto-sidebar=1)![image](https://github.com/decentdao/fractal-interface/assets/18615633/3f05923c-4ed0-4e22-8e42-531dad1a0dcc)

**Comment by Da-Colon** [comment]
> No setting gear on those children plz
> […](#)

Do you mean on the current DAO only? (as it might not always be the parent DAO)

**Comment by Da-Colon** [comment]
> > Didn't noticed your change there to re-add the settings menu. Now someone else correct me but do we need this functionality to be on the Hierarchy page (my Opinion, no)? If yes, should it match the gear icon on DAO Dashboard?
> 
> Yep good catch. [Updated in Figma](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?m=auto&node-id=122%3A13462&t=JZsXE75rQ5gEjGv7-1)
> 
> [Updated Prototype ](https://www.figma.com/proto/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?page-id=122%3A13462&node-id=2746-5942&viewport=899%2C-77%2C0.21&t=VkGEryQ1YNCJ0WB1-1&scaling=scale-down&starting-point-node-id=2746%3A5942&show-proto-sidebar=1)![image](https://private-user-images.githubusercontent.com/18615633/329743031-3f05923c-4ed0-4e22-8e42-531dad1a0dcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzODk5MDYsIm5iZiI6MTcxNTM4OTYwNiwicGF0aCI6Ii8xODYxNTYzMy8zMjk3NDMwMzEtM2YwNTkyM2MtNGVkMC00ZTIyLThlNDItNTMxZGFkMWEwZGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAxMDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZTYyOTQ2MzdjMGMzZWI4ZDViMjBjMWUzNGQ2OWVlYjJlN2NiM2RlYTE4YTkzYTMyMTA3NWJmZjI0NGNlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8tqevNLAGVlA4Ojlqw3uUIalpwb2l05ylSbNWbqomI)

Heard on that. Do the Info cards on the DAO dashboard have this over states?

**Comment by adamgall** [comment]
> > No setting gear on those children plz
> > […](#)
> 
> Do you mean on the current DAO only? (as it might not always be the parent DAO) @adamgall

I just meant that I think we don't need to display a "settings" icon on any DAO in the hierarchy which is not the "currently loaded" DAO.

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1764
