### ISSUE TITLE
Treasury Page Transactions overlapping

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1721]
1) Treasury page Txs getting criss crossed on mobile
![WhatsApp Image 2024-05-06 at 13 19 05 (3)](https://github.com/decentdao/fractal-interface/assets/31554133/cd4da457-2bb1-48a8-a86e-80323f207508)

_Originally posted by @tomstuart123 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2096397063_

**Comment by Da-Colon** [comment]
How should this look? (I need a design `@` for github @adamgall lol)

**Comment by tomstuart123** [comment]
@xraystyle1980 / @nicolaus-sherrill any quick takes here?

**Comment by xraystyle1980** [comment]
> @xraystyle1980 / @nicolaus-sherrill any quick takes here?

Full width table and allow user to horizontally scroll the tx table side to side

**Comment by nicolaus-sherrill** [comment]
@tomstuart123 let's follow @xraystyle1980 's lead right now. I need to do more research on mobile table best practices. Tables kinda suck on mobile, so I'd prefer to avoid or optimize.

Off the cuff, that text looks _really_ big for consisting entirely of utility info vs communicating action. Could we push that text size down?

**Comment by xraystyle1980** [comment]
@nicolaus-sherrill reminder I have a couple treasury mobile patterns we can formalize if need be

**Comment by nicolaus-sherrill** [comment]
@xraystyle1980 yeah let's get non-design eyes on what you have right now.

**Comment by adamgall** [comment]
> How should this look? (I need a design `@` for github @adamgall lol)

@Da-Colon you got it: @decentdao/designers

**Comment by xraystyle1980** [comment]
> @xraystyle1980 yeah let's get non-design eyes on what you have right now.

Non design eyes please look at [Treasury Mobile concepts here](https://www.figma.com/design/7zqmHjIfoxVDDx7wZw6xqI/Design-%26-Feedback?node-id=1156-26171&t=nYyFtK0DFI7kofLP-4)

@tomstuart123 thoughts on the design overall? @adamgall @mudrila @Da-Colon thoughts on execution? 🙏

**Comment by adamgall** [comment]
@xraystyle1980 i think this design looks great! don't see any reason why it would be particularly. difficult. Do you have a rendering of what the expanded coins/assets sections would look like?

**Comment by tomstuart123** [comment]
@xraystyle1980 onboard. I like bringing assets up and obscuring coins/assets until required. +1 @adamgall on getting that view for devs. Whoever, executes this, if that piece ends up being tricky, we can always do the collapsable piece after

Also interested how the movement of 'send assets on own row' transitions as responsive changes. 

Overall, excited for this though

**Comment by tomstuart123** [comment]
Awesome. Thanks @mudrila . let us know how it goes and whether you just starter implement the Txs component (my recommendation) or implement the whole mobile redesign

**Comment by tomstuart123** [comment]
love it

**Comment by adamgall** [comment]
Closed via #1790
