### ISSUE TITLE
App crash when no assets in treasury

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1723]
1) when I click send assets but there are no assets in the treasury 
https://github.com/decentdao/fractal-interface/assets/31554133/3ab482cf-e796-4c19-a1a1-2bb0f343c66f
![Screenshot 2024-05-06 at 13 03 24](https://github.com/decentdao/fractal-interface/assets/31554133/b4933f2c-4ad7-418b-b2c5-ca8630bdedcf)

_Originally posted by @tomstuart123 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2096401964_

**Comment by tomstuart123** [comment]
@mudrila can you confirm if you're working on this? If so, please assign self

**Comment by adamgall** [comment]
@mudrila 

This is still broken for me:

https://deploy-preview-1578.app.dev.fractalframework.xyz/treasury?dao=sep:0x42D5D9d7483FF241160E00D6F2a3c7761A5E29e1


![Image](https://github.com/decentdao/fractal-interface/assets/706929/8d98c700-b72f-4e98-aa3a-d0c2cba485d6)

**Comment by tomstuart123** [comment]
I've approved 1723. Once one more has approved, lets close this issue

**Comment by adamgall** [comment]
Closed by https://github.com/decentdao/fractal-interface/pull/1755
