### ISSUE TITLE
App crash "couldn't read .no of undefined"

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1724]
It happened again but not on the treasury page> I couldn't consistently replicate this one

![Screenshot 2024-05-06 at 12 54 43](https://github.com/decentdao/fractal-interface/assets/31554133/136e141a-5958-4460-ad95-38fed7a24afa)

![WhatsApp Image 2024-05-06 at 13 19 05](https://github.com/decentdao/fractal-interface/assets/31554133/d3ce92d3-778e-4c69-921a-2f08828c9d78)

_Originally posted by @tomstuart123 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2096404483_

**Comment by Da-Colon** [comment]
Looks like an issue of the DAO type not being correct and a value trying to type convert is failing

**Comment by tomstuart123** [comment]
Sadly not. The only consistent time I saw it was clicking send assets. 

I'll keep doing desktop and mobile testing up to Parker's event on the 26th. If it happens again I'll write down the exact flow

**Comment by DarksightKellar** [comment]
Did some blind codebase investigation based of error message. Opened a PR that _MIGHT_ (emphasis) fix this: https://github.com/decentdao/fractal-interface/pull/1736

**Comment by adamgall** [comment]
Possibly fixed via https://github.com/decentdao/fractal-interface/pull/1736
