### ISSUE TITLE
Need background blur behind drop down menu

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1726]
Need background blur behind drop down menu

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiJlMWYwZjdmMy0xOTNjLTRlMTctYjBjYS1mNmM5NzY4MTUwYmQifQ==)

<details><summary>Browser metadata</summary>

```
Path:      /
Browser:   Chrome 124.0.0.0 on Mac OS 10.15.7
Viewport:  1708 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=124.0&resolution=1708x1027&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663ba7f8180cc1007f8695b0&resolution=resolved)

_Originally posted by @xraystyle1980 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2100956754_

**Comment by Da-Colon** [comment]
Duplicate, see #1684
