### ISSUE TITLE
App not scrolling after allocation

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1728]
After allocation, the app did not scroll to the top. 
<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Mobile Safari 17.4.1 on iOS 17.4.1
Viewport:  393 x 659 @3x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fcreate&os=iOS&os_version=17.4&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663ba941cc87930089124eb0&resolution=resolved)

_Originally posted by @azadikoff in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2100965841_

**Comment by adamgall** [comment]
@azadikoff what is this in reference to?

**Comment by azadikoff** [comment]
On mobile, I allocated tokens and hit "next". The next page/set of fields loaded but the field of view was not at the top of the form.
