### ISSUE TITLE
Mobile view doesn't display whole site by default

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1731]
**dara.khan left a comment:**

When I log in on mobile, I have to pinch to zoom out to see everything. Can't share screenshot on netlify mobile tho...looks different from desktop 
<details><summary>Browser metadata</summary>

```
Path:      /
Browser:   Chrome 124.0.0.0 on Android 10
Viewport:  559 x 1035 @2.625x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2F&os=Android&os_version=10&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bac25180cc100a88698af&resolution=resolved)

_Originally posted by @netlify[bot] in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2100994293_

**Comment by adamgall** [comment]
@SpookyAction-BTC, lacking more information, closing this in as duplicate of https://github.com/decentdao/fractal-interface/issues/1722

Please feel free to re-open with some screenshots of what you're seeing, if your feedback is different than @tomstuart123's.

**Comment by SpookyAction-BTC** [comment]
@adamgall hey will get a screenshot. We should re-open. This is different. I'm on Android, Pixel 6, CB Wallet Browser and Chrome. When I'd reach the main page, it would be zoomed in and elements like the boxes, etc. were cut off. I had to pinch to zoom out to see the whole app. Will re-create and turn around asap

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1775
