### ISSUE TITLE
New "error" designs for top nav search

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1734]
From @xraystyle1980:  Updated the design system to add error state to top nav search
[In Figma](https://www.figma.com/file/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?type=design&node-id=1673%3A14186&mode=dev)
![image](https://github.com/decentdao/fractal-interface/assets/18615633/b49fd6e3-cf55-44c6-add3-a620cbbbd30a)

**Comment by nicolaus-sherrill** [comment]
@mudrila I am getting this beast when I enter anything into the search bar now. I left a comment about this yesterday.
<img width="1407" alt="Screenshot 2024-05-09 at 12 36 27 PM" src="https://github.com/decentdao/fractal-interface/assets/62394931/81b07ac9-6e53-40e5-8c9e-4ad7e9cd0667">

**Comment by adamgall** [comment]
Give the app a refresh and try again. A fix for this was just merged.

**Comment by nicolaus-sherrill** [comment]
Muuuuch better.

**Comment by tomstuart123** [comment]
love it :)
