### ISSUE TITLE
All text is italicized on mobile

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1735]
[uploading...]

All text is italicized on mobile 
<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Mobile Safari 17.4.1 on iOS 17.4.1
Viewport:  393 x 659 @3x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fcreate&os=iOS&os_version=17.4&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bad0753262b0309a73a82&resolution=resolved)

_Originally posted by @azadikoff in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101001454_

**Comment by adamgall** [comment]
@azadikoff not sure what you mean by this. Also looks like whatever you were trying to upload didn't finish when you submitted the issue.

**Comment by azadikoff** [comment]
Strange. Here's the screenshot ![image](https://github.com/decentdao/fractal-interface/assets/295904/3f8d4779-d8b7-4c5a-8736-df5807527c7e)

**Comment by adamgall** [comment]
This is the first anyone has reported this. Might be just a you thing? Do you see this on different mobile browsers?

**Comment by azadikoff** [comment]
Same in safari and brave for me on mobile.

**Comment by tomstuart123** [comment]
weird. I don't see it on android/chrome mobile


Could one of you check with an iphone? @adamgall @Da-Colon @mudrila @xraystyle1980  

Similar to this - https://github.com/decentdao/fractal-interface/issues/1733

Might be worth checking the whole flow on an iphone as most of the mobile testing has been done by me on android

**Comment by xraystyle1980** [comment]
I'm getting this on iPhone 14 in Chrome and Arc (chromium) and in Firefox. Also, Firefox mobile not loading background color
![IMG_3284](https://github.com/decentdao/fractal-interface/assets/18615633/50df1ca1-c0bd-40e2-8f51-9fa7adf54c4b)
![IMG_3285](https://github.com/decentdao/fractal-interface/assets/18615633/52da513f-f4f1-4597-b8c9-1a3209b0abc3)
![IMG_3286](https://github.com/decentdao/fractal-interface/assets/18615633/b0af1b15-b3ad-4cb4-b725-fb0acfb11344)

**Comment by adamgall** [comment]
Well damn this is fucked wtf

**Comment by adamgall** [comment]
@mudrila it looks like we already have woff/woff2 files in the codebase. why did you attempt to regenerate them from the ttf?

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1780
