### ISSUE TITLE
Full sentence needs a period

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1739]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYmVlNWZhYTA4OWIwMDA5ODJhODg4IiwiaWQiOiJlNDJlZmZkMC0xYTM0LTRjNDAtYmJjZS0xNzEyMjIwY2RjZDQifQ==)

Full sentences need a period
<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Chrome 124.0.0.0 on Mac OS 10.15.7
Viewport:  1720 x 717 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fcreate&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=124.0&resolution=1720x717&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663bee5faa089b000982a888&commentID=663c3066d9697c3cbdec32fa&resolution=resolved)

_Originally posted by @netlify[bot] in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101801880_

**Comment by DarksightKellar** [comment]
This is purely personal preference, but I disagree.

This is purely personal preference, but I disagree

---

Something I read a while back - that made sense to me in retrospect - about communication via text and the difference in perception between single-sentence texts sent with and without a period: One of them feels... abrupt, almost standoff-ish. The other more, I dunno, friendly? Mentally parseable? 

Or maybe it's just me. Not a hill I'm willing to die (or even stay) on.

**Comment by adamgall** [comment]
I think full sentences need periods too.

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1760
