### ISSUE TITLE
"Wrong network" page design

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1743]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiI3ZTMyZGYxMy01NjIwLTRkY2MtYjY0My1kZmE1MWQwYzMzYzYifQ==)

@design team — when viewing a DAO while connected to the wrong network, this screen appears. This appears to be an additional error screen than what we already designed. 

This is a nice-to-have, but we should get a properly designed version of this. Something with better visual hierarchy and ability to change network.
<details><summary>Browser metadata</summary>

```
Path:      /home?dao=eth:0xD26c85D435F02DaB8B220cd4D2d398f6f646e235
Browser:   Firefox 125.0 on Mac OS 10.15
Viewport:  1402 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fhome%3Fdao%3Deth%3A0xD26c85D435F02DaB8B220cd4D2d398f6f646e235&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=125.0&resolution=1402x912&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/home?dao=eth:0xD26c85D435F02DaB8B220cd4D2d398f6f646e235) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bae141b3b4803faf4d351&resolution=resolved)

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101008335_

**Comment by nicolaus-sherrill** [comment]
@xanaramoss can you get something spun up that matches those other error pages? Tag @xraystyle1980 in for handoff.

**Comment by xanaramoss** [comment]
> @xanaramoss can you get something spun up that matches those other error pages? Tag @xraystyle1980 in for handoff.

@xraystyle1980 [here it goes.](https://www.figma.com/file/7zqmHjIfoxVDDx7wZw6xqI/Design-%26-Feedback?type=design&node-id=1250-5957&mode=design&t=PElN3p6bDpkkPznH-4)

Not sure if the "Go Home" button is supposed to be there. I leave it to you! 🤙

**Comment by xraystyle1980** [comment]
> > @xanaramoss can you get something spun up that matches those other error pages? Tag @xraystyle1980 in for handoff.
> 
> @xraystyle1980 [here it goes.](https://www.figma.com/file/7zqmHjIfoxVDDx7wZw6xqI/Design-%26-Feedback?type=design&node-id=1250-5957&mode=design&t=PElN3p6bDpkkPznH-4)
> 
> Not sure if the "Go Home" button is supposed to be there. I leave it to you! 🤙

Thanks @xanaramoss 
Are you OK with the stethoscope illustration bottom being cropped in mobile? (see below)
[In Figma](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?m=auto&node-id=2705%3A4580&t=CG2O0kSzdRJpSX0d-1)

*I removed the Go Home and Leave Feedback actions since the intended action is for user to switch networks and have the page show the correct data. If not working user has the "Leave Feedback" floating button in the bottom right.
![image](https://github.com/decentdao/fractal-interface/assets/18615633/e15b293f-054f-4ddb-9b09-d591e3d01f2f)

**Comment by xraystyle1980** [comment]
I went ahead and added desktop and mobile designs to handoff. Note: these designs do NOT contain the Go Home and Leave Feedback actions. 

[Handoff is here](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=2705-4581&t=CG2O0kSzdRJpSX0d-4)

@nicolaus-sherrill for visibility

**Comment by xanaramoss** [comment]
> > > @xanaramoss can you get something spun up that matches those other error pages? Tag @xraystyle1980 in for handoff.
> > 
> > 
> > @xraystyle1980 [here it goes.](https://www.figma.com/file/7zqmHjIfoxVDDx7wZw6xqI/Design-%26-Feedback?type=design&node-id=1250-5957&mode=design&t=PElN3p6bDpkkPznH-4)
> > Not sure if the "Go Home" button is supposed to be there. I leave it to you! 🤙
> 
> Thanks @xanaramoss Are you OK with the stethoscope illustration bottom being cropped in mobile? (see below) [In Figma](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?m=auto&node-id=2705%3A4580&t=CG2O0kSzdRJpSX0d-1)
> 
> *I removed the Go Home and Leave Feedback actions since the intended action is for user to switch networks and have the page show the correct data. If not working user has the "Leave Feedback" floating button in the bottom right. ![image](https://private-user-images.githubusercontent.com/18615633/329701701-e15b293f-054f-4ddb-9b09-d591e3d01f2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzE0MDksIm5iZiI6MTcxNTM3MTEwOSwicGF0aCI6Ii8xODYxNTYzMy8zMjk3MDE3MDEtZTE1YjI5M2YtMDU0Zi00ZGRiLTliMDktZDU5MWUzZDAxZjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE5NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMjM1YjVkOThhNmYxYTRkNTk2ZGViNzAxNjMwNzY2NjMyMzQ3NDIyNDNiMTRkNjgxZjY0NDg1NzUzNGM3YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kQTU_0NsIQdnwEDEBz25zdiM8iPCrExxhCSSpe4JZLo)

Looks nice @xraystyle1980 🩺👌

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1783
