### ISSUE TITLE
Snapshot Space missing

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1746]
from Adam: I think there might be an issue for this already? Think that the text is there it's just the same color as the input box.

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiJiNDY5ZjQ5Zi1kNmNkLTQxMjAtYWU5Mi01NGVjZjM5ZWZlMmUifQ==)
I added a snapshot space but it doesn't show here, and i wanted to remove it

<details><summary>Browser metadata</summary>

```
Path:      /settings?dao=sep:0x329d13a13d82d1fb5d3A7D14C5a2417AFf525768
Browser:   Chrome 124.0.0.0 on Mac OS 10.15.7
Viewport:  1544 x 1020 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fsettings%3Fdao%3Dsep%3A0x329d13a13d82d1fb5d3A7D14C5a2417AFf525768&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=124.0&resolution=1544x1020&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/settings?dao=sep:0x329d13a13d82d1fb5d3A7D14C5a2417AFf525768) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663badeefbc5a700ab199cba&resolution=resolved)

_Originally posted by @azadikoff in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101007374_

**Comment by adamgall** [comment]
Believe this is a duplicate of https://github.com/decentdao/fractal-interface/issues/1749.

@azadikoff can you please share your Sepolia DAO address?

**Comment by azadikoff** [comment]
0xb69FB5068AF1d3b1Ae1BC8CC8D37E12F83FEFAe4

**Comment by adamgall** [comment]
> 0xb69FB5068AF1d3b1Ae1BC8CC8D37E12F83FEFAe4

@azadikoff this doesn't look like a DAO address.. is this your EOA address? I meant, what is the address of the DAO you deployed / were posting transactions to on wendesday.

**Comment by adamgall** [comment]
Confirmed that the snapshot space _is_ set for this DAO, it's just not "visible" in the settings because the text is the same color as the input background.

https://deploy-preview-1578.app.dev.fractalframework.xyz/settings?dao=sep:0x329d13a13d82d1fb5d3A7D14C5a2417AFf525768

<img width="932" alt="Screenshot 2024-05-10 at 11 08 27 AM" src="https://github.com/decentdao/fractal-interface/assets/706929/31526fa6-14bf-4a04-bde2-1b337ce57bde">

Closing this issue as a duplicate of #1749
