### ISSUE TITLE
Settings page input boxes text same as background

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1749]
Update: I believe this to be due to NOT having delegated voting tokens. After I delegated my tokens I was able to edit. 
Note: the DAO name IS there (try to highlight/select it) but can't be seen, is same color as input

Can't edit DAO name or snapshot URL

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiIyMzVkMDM3ZC04NGE3LTRmNjAtOTEyNS04NDliYWQzY2JkM2YifQ==)

<details><summary>Browser metadata</summary>

```
Path:      /settings?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2
Browser:   Chrome 124.0.0.0 on Mac OS 10.15.7
Viewport:  1708 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fsettings%3Fdao%3Dsep%3A0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=124.0&resolution=1708x1027&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/settings?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bad5be4a6a303681d58db&resolution=resolved)

_Originally posted by @xraystyle1980 in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101003649_

**Comment by nicolaus-sherrill** [comment]
@xraystyle1980 I left comments in the components page. Please update disabled placeholder designs so they are more visually distinct from the default states and more clearly indicate a "disabled" state.



Lower priority before launch.

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1752
