### ISSUE TITLE
Language Menu location on Mobile

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1756]
@decentdao/designers where should the language menu appear on mobile? on mobile. the entire menu itself is full screen, so there's no room at the right. 

See the language menu way on the right there:
![Screenshot 2024-05-09 at 5 16 08 PM](https://github.com/decentdao/fractal-interface/assets/706929/71163254-3d61-418b-8400-e5e45821ae3d)

**Comment by nicolaus-sherrill** [comment]
@xraystyle1980 think you can tackle this one while you're in mobile-optimization mode?

Need: Mobile nested menu pattern.

I saw you putting that work in on the network selection nested dropdown, so keep pulling that thread.

**Comment by xraystyle1980** [comment]
Ready to go in [Product Handoff](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?m=auto&node-id=3045%3A6438&t=RAj8FglGGysznikl-1)
In [Design System](https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?m=auto&node-id=3224%3A510&t=3I9KompgrpHOjQ0Z-1)



![Image](https://github.com/decentdao/fractal-interface/assets/18615633/ca6b09e5-36be-45de-bb57-89cbf2dd3b81)

**Comment by adamgall** [comment]
Closing in favor of https://github.com/decentdao/fractal-interface/issues/1795
