### ISSUE TITLE
DAO Hierarchy Node Card Gear Icon and Active states

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/fractal-interface#1773]
Matt: updated the [Hierarchy handoff to include a prototype](https://www.figma.com/proto/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?page-id=122%3A13462&node-id=2746-5942&viewport=1037%2C-346%2C0.35&t=57SJEp8vmUSy3SkE-1&scaling=scale-down&starting-point-node-id=2746%3A5942&show-proto-sidebar=1) to show clicking on the full card should switch organizations.

*Also includes hover and active states for the hierarchy cards.

Matt: I added the three dots icon-button to these designs. I can't recall if we removed them intentionally or they just didn't make it to the reskin design. @tomstuart123 can you weigh in here?

**Comment by tomstuart123** [comment]
I personally prefer having the gear icon at hierarchy. Especially adding sub-safes feels very intuitive from here

I think we removed them just becuase we implemented 'click entire card'

If we can make a way to make both work together @xraystyle1980 , this would be my choice

**Comment by xraystyle1980** [comment]
> I personally prefer having the gear icon at hierarchy. Especially adding sub-safes feels very intuitive from here
> 
> I think we removed them just becuase we implemented 'click entire card'
> 
> If we can make a way to make both work together @xraystyle1980 , this would be my choice

@Da-Colon will this be tricky to implement with the current design the way it is?

**Comment by Da-Colon** [comment]
@xraystyle1980 We discussed this during standup. for now. This task has turned into just getting the active/hover states and re-adding the whole card linking. 

Further discussion is going to happen about if we need the gear icon at all on this page, and if yes we talked about figuring out a way where we don't have nested links.
