### ISSUE TITLE
Firefox mobile background color missing

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1784]
@adamgall I’m still not seeing the background color in Firefox mobile. Italics went away though 👍
![May 14 Screenshot from Matt](https://github.com/decentdao/fractal-interface/assets/18615633/6819d704-734f-44d0-82f6-6b5c9f6c2ebe)

<details><summary>Browser metadata</summary>
```
Path:      /
Browser:   Firefox 125.3 on iOS 17.4.1
Viewport:  393 x 793 @3x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1780.app.dev.fractalframework.xyz%2F&os=iOS&os_version=17.4&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1780.app.dev.fractalframework.xyz/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6643814c04e74000089dcddd&commentID=6643965e8f3c18092df43830&resolution=resolved)

_Originally posted by @xraystyle1980 in https://github.com/decentdao/fractal-interface/issues/1780#issuecomment-2110694270_

**Comment by adamgall** [comment]
@mudrila indeeed. i'll pick this up

**Comment by adamgall** [comment]
@xraystyle1980 I'm unable to recreate this.

Both the deploy preview URL your screenshot is from, and the latest version of the codebase, result in the correct background color of the home page for me on iOS Firefox.

Can anyone else recreate?

@decentdao/design @decentdao/product @decentdao/marketing @decentdao/engineering ?

**Comment by xanaramoss** [comment]
> @xraystyle1980 I'm unable to recreate this.
> 
> Both the deploy preview URL your screenshot is from, and the latest version of the redesign codebase at https://deploy-preview-1578.app.dev.fractalframework.xyz/, result in the correct background color of the home page for me on iOS Firefox.
> 
> iOS in Light Mode: ![Image](https://private-user-images.githubusercontent.com/706929/330563985-90b88e0e-a544-479c-bfee-b880bd4e8395.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjkzNTYsIm5iZiI6MTcxNTc2OTA1NiwicGF0aCI6Ii83MDY5MjkvMzMwNTYzOTg1LTkwYjg4ZTBlLWE1NDQtNDc5Yy1iZmVlLWI4ODBiZDRlODM5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxMDMwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmI5NjY4NTZjYzY1ZGQwMzRjYjM0MzYzZjQ5NDE0OTU5M2E2YTFjOTk4M2ZkNWNlYTQzNmQyM2JjNzU3MWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2rcwl-p4qbWQfv3nYFYhmdDh48-gXcphUhtNHb2_sEI)
> 
> iOS in Dark Mode: ![Image](https://private-user-images.githubusercontent.com/706929/330564277-3b386667-0275-417d-82b2-0f63473b3fc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjkzNTYsIm5iZiI6MTcxNTc2OTA1NiwicGF0aCI6Ii83MDY5MjkvMzMwNTY0Mjc3LTNiMzg2NjY3LTAyNzUtNDE3ZC04MmIyLTBmNjM0NzNiM2ZjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxMDMwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmViNmJiMzZiNmYzYmQzOWE2MWRmZGNiYWFiZTA0NDBlNWMyM2JkMDJjOGUxYzdjMWI1YWE1MjczNjlhYmM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RP56H3AGrJ3fgCOATXT5laXPsb2SYtZSCmGRsLrPz6w)
> 
> Can anyone else recreate?
> 
> @decentdao/design @decentdao/product @decentdao/marketing @decentdao/engineering ?

I tested it and it's showing the correct colors! 
ios Firefox, Chrome + Safari. 👌

**Comment by adamgall** [comment]
@xraystyle1980 ok, so it's a personal setting?

Are you saying that there's anything we should do about this behavior?

**Comment by xraystyle1980** [comment]
> @xraystyle1980 ok, so it's a personal setting?
> 
> Are you saying that there's anything we should do about this behavior?

Correct. Appears to be a personal setting. I don't think there's anything we need to do at the moment. It is good to know and be aware of system settings like day/night mode and how a browser like Firefox iOS will invert colors one way or the other. Ultimately having a proper light mode should mitigate this. (i.e., if the user can easily toggle and switch the UI I don't see this being a WTF moment) 
@adamgall feel free to close
@nicolaus-sherrill 👋 for visibility
