### ISSUE TITLE
Dashboard Info Card responsiveness Update

### ISSUE THREAD

**Issue by Da-Colon** [decentdao/fractal-interface#1789]
Noticed that when looking at this on smaller screens. (Smaller than 1300px) the three components escape parent container until the components wrap. 

![Image](https://github.com/decentdao/fractal-interface/assets/38386583/6fce2480-6ce0-446c-82da-ce81047b4f9e)

**Comment by adamgall** [comment]
@decentdao/design can you instruct how these components should break as the screen size changes?

**Comment by xanaramoss** [comment]
> @decentdao/design can you instruct how these components should break as the screen size changes?
<img width="873" alt="Screenshot 2024-05-15 at 11 27 17" src="https://github.com/decentdao/fractal-interface/assets/162434678/6673cf29-fc7d-4dd1-8f62-7f32910cf61c">

@xraystyle1980 has those designed on the Product Handoof Files.
[DAO Home page link.](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=234-28910&t=mPCnFyzIllnFaggM-4)

**Comment by xraystyle1980** [comment]
> Update: This turns out to be a responsiveness issue, more broadly for the DAO Info cards as a how. Talked to @xraystyle1980 this morning. Will be following up later

Adding screenshots of responsive behavior in app:

![1400](https://github.com/decentdao/fractal-interface/assets/18615633/29c2af29-e12f-4267-8000-4c0d6514d1cb)
![1024](https://github.com/decentdao/fractal-interface/assets/18615633/7733d9b6-8c4c-434f-aab1-b0fe48427776)
![768](https://github.com/decentdao/fractal-interface/assets/18615633/5aedfa78-23c7-499f-823e-a0f833c1a017)
![767](https://github.com/decentdao/fractal-interface/assets/18615633/be5fdca6-91dd-42b3-ab93-0b16fcf85e35)
![919](https://github.com/decentdao/fractal-interface/assets/18615633/62d53484-9db0-4c58-81c3-cc86dff2146c)
![375 no parent](https://github.com/decentdao/fractal-interface/assets/18615633/c04cfcd9-13cb-4751-a8c5-fcee302f3bff)
![525](https://github.com/decentdao/fractal-interface/assets/18615633/2625b108-4446-4f18-880a-170df5b9ca22)
![375 long name and parent](https://github.com/decentdao/fractal-interface/assets/18615633/bbb61333-bbfb-4aa6-a52a-caa835ae2fe4)
![422 long name and parent](https://github.com/decentdao/fractal-interface/assets/18615633/c7d79727-4c68-4cbd-ba5c-2888abde033c)
