### ISSUE TITLE
Quorum bug - Proposal details

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/fractal-interface#1793]
In testing a PR, I noticed a bug in the reskin proposal details

As you can see in screenshot below, this proposal passed with me holding 10 tokens out of 14.  This should have caused the quorum bar on the right to be fully filled (i.e show that quorum is passed). Instead the quorum bar remained stuck at 4% (which is the % quorum of the DAO; not its current quorum). 

![Image](https://github.com/decentdao/fractal-interface/assets/31554133/08d4f9a0-fb18-45d3-beeb-231a87d0bcec)

The proposal has since gone through timelock, executable and exceucted, so that is all functioning correctly.

![Image](https://github.com/decentdao/fractal-interface/assets/31554133/5744f7f7-136f-4060-8020-23d99175ac71)

i.e. its just the quorum bar in proposal details. 

To test yourself DAO link here - https://deploy-preview-1578.app.dev.fractalframework.xyz/proposals/1?dao=sep:0x7E9308800b7F3234982867b95481C8242C8AbFD1

**Comment by adamgall** [comment]
@tomstuart123 the UI says you held 12 tokens, not 10. can you confirm your voting weight here?

**Comment by tomstuart123** [comment]
you are correct it was 12 tokens out of a total of 14 (2 were in the treasury)

**Comment by adamgall** [comment]
thanks for confirming @tomstuart123 

Is there language anywhere describing how exactly that quorum bar is supposed to work? Both in terms of "how full it is" and the various numbers that are displayed within it and underneath it?

**Comment by tomstuart123** [comment]
Note, @decentdao/design can you check the figma designs track this. I think we may have missed when we updated this and need updates to the figma

**Comment by tomstuart123** [comment]
More clarity on my issue @DarksightKellar / @adamgall 

I'm getting two visualisations of the quorum component within the same root reskin branch:

version 1 sepolia token voting dao
--> https://deploy-preview-1578.app.dev.fractalframework.xyz/proposals/1?dao=sep:0x7E9308800b7F3234982867b95481C8242C8AbFD1

![Screenshot 2024-05-16 at 16 58 20](https://github.com/decentdao/fractal-interface/assets/31554133/03857e24-37ba-42aa-9909-c85c2e8a5d25)

version 2 mainnet token voting dao
--> https://deploy-preview-1578.app.dev.fractalframework.xyz/proposals/17?dao=eth:0x36bD3044ab68f600f6d3e081056F34f2a58432c4
![Screenshot 2024-05-16 at 16 58 37](https://github.com/decentdao/fractal-interface/assets/31554133/5cc1c89b-c718-45da-9b96-bbb1a22e8ed8)

The latter is the only version we want users to see across mainnet or sepolia

Does that make sense? Not sure if it's actually to do with the chain or if something else is causing this

**Comment by tomstuart123** [comment]
@DarksightKellar happy to jump on if this doesn't make sense from 6pm uk onwards
