### ISSUE TITLE
Create new Home page Skeleton

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1798]
https://www.figma.com/design/7zqmHjIfoxVDDx7wZw6xqI/Design-%26-Feedback?node-id=1751-5030&t=Pzzo5cVZdeHdSHOV-0

This issue is just for creating a skeleton of the new home page design.

This issue will be complete when the new Home page contains

- decent logo
- the existing search bar
  - (changes to search to happen in another issue)
- a placeholder element for the "Create Safe" button
  - (creating the actual button and it's behavior to happen in another issue)
- a placeholder element for the "My Safes" component
  - (creating this component and its behavior to happen in another issue)
- the "Read Docs" link

Other notes:
- Make sure the Footer is at the bottom of the viewport, if there's not enough content in the viewport to enable scrolling.

**Comment by tomstuart123** [comment]
nice @adamgall . Great starter template

As written in related issue, assuming font/button come later so I'll approve for now.

One note is around the footer. When I open it on mobile view in dev tools, the footer is always visible on open. On my mobile in chrome though, you have to scroll for the footer

**Comment by adamgall** [comment]
Closed via #1805
