### ISSUE TITLE
Desktop + Mobile deploy DAO inability

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/fractal-interface#1816]
**dara.khan left a comment:**

![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY0NzgwODkyYzg2YzIwMDA4OGI1Nzg5IiwiaWQiOiIxMzY5NWNlNy1hZjY5LTRmNjktOTg1NS04MmNjYTcxZGY0MWEifQ==)

Unable to deploy my DAO on desktop 😢 

<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Chrome 124.0.0.0 on Mac OS 10.15.7
Viewport:  1011 x 816 @1x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fcreate&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=124.0&resolution=1011x816&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=664780892c86c200088b5789&commentID=664788228c65b1f3174cda57&resolution=resolved)

_Originally posted by @netlify[bot] in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2117977846_

**Comment by adamgall** [comment]
I cannot replicate this.

I just attempted this same workflow on my machine:

- Decent UI via Chrome on MacOS Desktop
- connected to Coinbase Wallet via iOS
- Create new Safe workflow
- Prompted to confirm transaction on CB Wallet on phone
- Approved transaction, Decent UI updated appropriately, transaction confirmed, everything updated as it should have.

@SpookyAction-BTC @tomstuart123 can we hop on a call if this is still an issue for you on https://app.dev.decentdao.org ?

**Comment by adamgall** [comment]
I did a bunch of testing with CB Wallet, which included the scenario in this issue:

https://github.com/decentdao/fractal-interface/issues/1733#issuecomment-2121150245

**Comment by tomstuart123** [comment]
thanks @adamgall . Shared my take here. https://decentdao.slack.com/archives/C06QZTUTKRC/p1716293869045069?thread_ts=1716236782.730649&cid=C06QZTUTKRC

Lets focus on 1) what we can reproduce AND 2) what blocks parker / nicolas specifically on pre-setup of the 'show DAOs'

**Comment by adamgall** [comment]
So @tomstuart123 , with that in mind, should we close this issue?

**Comment by tomstuart123** [comment]
yep close.
