### ISSUE TITLE
This network error message is very confusing.

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/fractal-interface#1820]
This network error message is very confusing.

The messaging is telling me which network I am connected to without telling me which network the Safe is on that I *should be* connected to. Suggest adjusting that copy to guide the user to which network they should be connected to.

Further, it's confusing that the app is referring to itself "Decent is connected to..." instead of addressing the user. (ex. "You are connected to..."). This makes me think that the error message is referring to the Safe name, which in this case is not Decent.

Lastly, the direction to the user to "try connection" is submissive in tone. Recommend changing that to something like "Please switch" "please connect..." etc.

![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY0NzgwODkyYzg2YzIwMDA4OGI1Nzg5IiwiaWQiOiJhN2IxYzYzYy05ODQ3LTQwM2YtYjA4MS1iMzI3NzUwMjJjZTQifQ==)

<details><summary>Browser metadata</summary>

```
Path:      /home?dao=sep:0x07D82EFcB2BEb403DB8B2B462289A7C7c2e3251f
Browser:   Firefox 125.0 on Mac OS 10.15
Viewport:  1678 x 910 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fhome%3Fdao%3Dsep%3A0x07D82EFcB2BEb403DB8B2B462289A7C7c2e3251f&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=125.0&resolution=1678x910&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/home?dao=sep:0x07D82EFcB2BEb403DB8B2B462289A7C7c2e3251f) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=664780892c86c200088b5789&commentID=66478bfe92f790fe7588a88e&resolution=resolved)

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2118009683_

**Comment by tomstuart123** [comment]
good call. I'm giving app copy one more look now I have xana / delma's feedback. Will share the updated doc with the copy here and review if this needs changing

**Comment by adamgall** [comment]
Closing this issue, it'll be handled with the new copy that's coming down the pike from @tomstuart123
