### ISSUE TITLE
Search Multisig  Add snapshot space --> Disabled DAO

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/fractal-interface#1827]
Steps I wanted:
1) Add a snapshot space to pre-existing multisig

Video shows the issue

Successful steps
1) paste multisig address and open DAO
2) create proposal of adding snapshot space. 
3) execute proposal

Then
1) hierarchy page got stuck on loading
2) when I went back to the app no proposals loaded (not even the executed one above)
3) settings page proposals all failed (dao name/ snapshot space)
4) Send assets button disappeared

Video - won't upload to github, so storing it here for you to view - [link](https://decentdao.slack.com/archives/C06QZTUTKRC/p1716213657896169?thread_ts=1716211628.206369&cid=C06QZTUTKRC)

DAO link here - https://deploy-preview-1578.app.dev.fractalframework.xyz/home?dao=sep:0xbA96a6B453da0309ee933E250F72085f9A5D8c11

**Comment by tomstuart123** [comment]
just replicated it again by doing the exact same steps but this time on mobile. 

Only difference was the executed proposal appears on mobile whilst it doesn't when I load it on desktop

Link to error DAO - https://deploy-preview-1578.app.dev.fractalframework.xyz/home?dao=sep:0x5a2a208554cAEBaE34D37dd2378dFD63107940a7

**Comment by adamgall** [comment]
Closed via #1835
