### ISSUE TITLE
snapshot space not adding to a Safe.app safe

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/fractal-interface#1836]
Follow on from https://github.com/decentdao/fractal-interface/pull/1835#pullrequestreview-2066644055

In short, safe.app created Safes are not bugging out the app now... but when I add a snapshot space, the list of snapshot proposals still doesn't open

see link - https://deploy-preview-1835.app.dev.decentdao.org/home?dao=sep:0xbA96a6B453da0309ee933E250F72085f9A5D8c11

Two executed proposals but no snapshot spaces

**Comment by Da-Colon** [comment]
@adamgall is working on this for extended from #1827
