### ISSUE TITLE
Add Plausible analytics tracking to Decent URL and subdomains

### ISSUE THREAD

**Issue by xraystyle1980** [decentdao/fractal-interface#1845]
Please add our Plausible Analytics tracking snippet to
`decentdao.org`
`app.decentdao.org`
`docs.decentdao.org`

`<script defer data-domain="decentdao.org" src="https://plausible.io/js/script.outbound-links.js"></script>
`

[Add the script to your website](https://plausible.io/docs/plausible-script)
[Hostname or subdomain tracking](https://plausible.io/docs/subdomain-hostname-filter#:~:text=Plausible%20helps%20you%20simplify%20cross,of%20your%20subdomains%20to%20another.)

**Comment by adamgall** [comment]
@xraystyle1980 it looks like plausible is already installed on decentdao.org via Webflow. Can you confirm?

I've just installed it also on docs.decentdao.org via GitBook, and also on app[.dev].decentdao.org via Netlify

**Comment by adamgall** [comment]
Tested, this is all working as expected.
